

// PAGE 5 DEPOTS LISTE AFFICHER 
##
GET http://localhost:3000/api/depots

## // PAGE 6 DEPOTS CARTES

GET http://localhost:3000/api/depots/674

##
// BONUS PAGE 5 AJOUTER UN DONNATEUR 
POST http://localhost:3000/api/personnes
Content-Type: application/json

{
  "nom": "Lio",
  "prenom": "Jean-Paul",
  "telephone": "0667888890",
  "adherente": true
}

### 201 - Enregistre un dépôt — personne_id, date_depot, type
POST http://localhost:3000/api/depots
Content-Type: application/json

{
  "personne_id": 3,
  "type": "boutique",
  "date_depot": "2026-10-15"
}





